CREATE TABLE UserBlog
(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    park VARCHAR(44) NOT NULL,
    description VARCHAR(8000) NOT NULL,
    rating VARCHAR(7) NOT NULL,
    user_id INT UNSIGNED,
    FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE PublicBlog
(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    park VARCHAR(44) NOT NULL,
    description VARCHAR(8000) NOT NULL,
    rating VARCHAR(7) NOT NULL,
    PRIMARY KEY (id)
);